### ISSUE TITLE
Set Semantic Type

### ISSUE THREAD

**Issue by seidinove** [usc-isi-i2/karma-step-by-step#2]
I am following the step-by-step instructions of the Karma tutorial (e.g., cloned karma step-by-step, renamed the folder karma, etc.). I successfully import museum-data.json and reach the step to set the semantic type of the first column, record_ID.  The following image shows the choices available for setting the semantic type of record_ID in the tutorial:
![set-semantic-type-window-from-tutorial](https://user-images.githubusercontent.com/37347660/37403047-f6588ade-2763-11e8-94ce-31091005a99f.png)

However, the following is what I see:
![set-semantic-type-window-actual](https://user-images.githubusercontent.com/37347660/37403095-1901a43a-2764-11e8-80c6-525ab832e5ac.png)

I'm still trying to pinpoint the cause of this.

**Comment by taheriyan** [comment]
This is expected. Karma learns the semantic types from previous
assignments, you have not assigned any semantic type yet, so there is no
training data to learn. You need to click on the Edit button and manually
select the semantic type, the system learns from that and suggests semantic
types for similar data (e.g., the same column if you load the source again).

**Comment by seidinove** [comment]
Thank you for your help, I'll close the issue.
